spring:
  application:
    name: gas-station-backend
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.plfdcshdyijssjqlepfo
    password: gassamramgas
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 60000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Flyway Configuration
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  


  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours

# Server Configuration
server:
  port: 8080

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Application Configuration
app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  security:
    jwt:
      header: Authorization
      prefix: "Bearer "
      expiration: 86400 # 24 hours in seconds

# Logging Configuration
logging:
  level:
    com.gasstation: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# MySQL Profile for Local Development
spring:
  config:
    activate:
      on-profile: mysql
  
  datasource:
    url: jdbc:mysql://localhost:3306/gasstation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: gasstation_user
    password: gasstation_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false

logging:
  level:
    com.gasstation: DEBUG
    org.springframework.security: DEBUG

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.gasstation: DEBUG
    org.springframework.security: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  
logging:
  level:
    com.gasstation: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN 